### ISSUE TITLE
Please don't create *.bak_clarius files

### ISSUE THREAD

**Issue by PhilipDaniels** [clariuslabs/TransformOnBuild#52]
They flash up temporarily in the VS 2017 solution window (causes questions from 'sensitive' developers!) and must be manually added to .gitignore in case they are accidentally left around.

**Comment by kzu** [comment]
@mnaoumov?

**Comment by mnaoumov** [comment]
@kzu I'll take a look

**Comment by bert-alpen** [comment]
Seconded. They create a problem when using TFS (which my company, unfortunately, still does).
Since in TFS all files are marked as ReadOnly by default, the write attempt in RewriteTemplateFile() generates an UnauthorizedAccessException. I tried to fix this by removing the ReadOnly flag in a pre build task, but apparently it only gets executed after this package.

**Comment by mnaoumov** [comment]
I'll fix it today

пн, 13 авг. 2018 г., 11:55 bert-alpen <notifications@github.com>:
